-- teams_country: add common_name and populate it
-- Safe to run once. If the column already exists, skip the ALTER.

ALTER TABLE teams_country
  ADD COLUMN common_name VARCHAR(255) NULL AFTER name;

-- Because name was previously overwritten with common names, copy name -> common_name first.
UPDATE teams_country
SET common_name = name
WHERE common_name IS NULL OR TRIM(common_name) = '';

-- Restore official formal names into name where we know the mapping.
UPDATE teams_country SET name = 'Arab Republic of Egypt' WHERE common_name = 'Egypt' OR name = 'Egypt';
UPDATE teams_country SET name = 'Argentine Republic' WHERE common_name = 'Argentina' OR name = 'Argentina';
UPDATE teams_country SET name = 'Bolivarian Republic of Venezuela' WHERE common_name = 'Venezuela' OR name = 'Venezuela';
UPDATE teams_country SET name = 'Co-operative Republic of Guyana' WHERE common_name = 'Guyana' OR name = 'Guyana';
UPDATE teams_country SET name = 'Commonwealth of Australia' WHERE common_name = 'Australia' OR name = 'Australia';
UPDATE teams_country SET name = 'Commonwealth of Dominica' WHERE common_name = 'Dominica' OR name = 'Dominica';
UPDATE teams_country SET name = 'Commonwealth of the Bahamas' WHERE common_name = 'Bahamas' OR name = 'Bahamas';
UPDATE teams_country SET name = 'Czech Republic' WHERE common_name = 'Czechia' OR name = 'Czechia';
UPDATE teams_country SET name = 'Democratic People''s Republic of Korea' WHERE common_name = 'North Korea' OR name = 'North Korea';
UPDATE teams_country SET name = 'Democratic Republic of São Tomé and Príncipe' WHERE common_name = 'São Tomé and Príncipe' OR name = 'São Tomé and Príncipe';
UPDATE teams_country SET name = 'Democratic Republic of the Congo' WHERE common_name = 'DR Congo' OR name = 'DR Congo';
UPDATE teams_country SET name = 'Democratic Republic of Timor-Leste' WHERE common_name = 'Timor-Leste' OR name = 'Timor-Leste';
UPDATE teams_country SET name = 'Democratic Socialist Republic of Sri Lanka' WHERE common_name = 'Sri Lanka' OR name = 'Sri Lanka';
UPDATE teams_country SET name = 'Federal Democratic Republic of Ethiopia' WHERE common_name = 'Ethiopia' OR name = 'Ethiopia';
UPDATE teams_country SET name = 'Federal Democratic Republic of Nepal' WHERE common_name = 'Nepal' OR name = 'Nepal';
UPDATE teams_country SET name = 'Federal Republic of Germany' WHERE common_name = 'Germany' OR name = 'Germany';
UPDATE teams_country SET name = 'Federal Republic of Nigeria' WHERE common_name = 'Nigeria' OR name = 'Nigeria';
UPDATE teams_country SET name = 'Federal Republic of Somalia' WHERE common_name = 'Somalia' OR name = 'Somalia';
UPDATE teams_country SET name = 'Federated States of Micronesia' WHERE common_name = 'Micronesia' OR name = 'Micronesia';
UPDATE teams_country SET name = 'Federation of Saint Christopher and Nevis' WHERE common_name = 'Saint Kitts and Nevis' OR name = 'Saint Kitts and Nevis';
UPDATE teams_country SET name = 'Federative Republic of Brazil' WHERE common_name = 'Brazil' OR name = 'Brazil';
UPDATE teams_country SET name = 'French Republic' WHERE common_name = 'France' OR name = 'France';
UPDATE teams_country SET name = 'Gabonese Republic' WHERE common_name = 'Gabon' OR name = 'Gabon';
UPDATE teams_country SET name = 'Grand Duchy of Luxembourg' WHERE common_name = 'Luxembourg' OR name = 'Luxembourg';
UPDATE teams_country SET name = 'Hashemite Kingdom of Jordan' WHERE common_name = 'Jordan' OR name = 'Jordan';
UPDATE teams_country SET name = 'Hellenic Republic' WHERE common_name = 'Greece' OR name = 'Greece';
UPDATE teams_country SET name = 'Independent and Sovereign Republic of Kiribati' WHERE common_name = 'Kiribati' OR name = 'Kiribati';
UPDATE teams_country SET name = 'Independent State of Papua New Guinea' WHERE common_name = 'Papua New Guinea' OR name = 'Papua New Guinea';
UPDATE teams_country SET name = 'Independent State of Samoa' WHERE common_name = 'Samoa' OR name = 'Samoa';
UPDATE teams_country SET name = 'Islamic Republic of Afghanistan' WHERE common_name = 'Afghanistan' OR name = 'Afghanistan';
UPDATE teams_country SET name = 'Islamic Republic of Iran' WHERE common_name = 'Iran' OR name = 'Iran';
UPDATE teams_country SET name = 'Islamic Republic of Mauritania' WHERE common_name = 'Mauritania' OR name = 'Mauritania';
UPDATE teams_country SET name = 'Islamic Republic of Pakistan' WHERE common_name = 'Pakistan' OR name = 'Pakistan';
UPDATE teams_country SET name = 'Italian Republic' WHERE common_name = 'Italy' OR name = 'Italy';
UPDATE teams_country SET name = 'Kingdom of Bahrain' WHERE common_name = 'Bahrain' OR name = 'Bahrain';
UPDATE teams_country SET name = 'Kingdom of Belgium' WHERE common_name = 'Belgium' OR name = 'Belgium';
UPDATE teams_country SET name = 'Kingdom of Bhutan' WHERE common_name = 'Bhutan' OR name = 'Bhutan';
UPDATE teams_country SET name = 'Kingdom of Cambodia' WHERE common_name = 'Cambodia' OR name = 'Cambodia';
UPDATE teams_country SET name = 'Kingdom of Denmark' WHERE common_name = 'Denmark' OR name = 'Denmark';
UPDATE teams_country SET name = 'Kingdom of Eswatini' WHERE common_name = 'Eswatini' OR name = 'Eswatini';
UPDATE teams_country SET name = 'Kingdom of Lesotho' WHERE common_name = 'Lesotho' OR name = 'Lesotho';
UPDATE teams_country SET name = 'Kingdom of Morocco' WHERE common_name = 'Morocco' OR name = 'Morocco';
UPDATE teams_country SET name = 'Kingdom of Norway' WHERE common_name = 'Norway' OR name = 'Norway';
UPDATE teams_country SET name = 'Kingdom of Saudi Arabia' WHERE common_name = 'Saudi Arabia' OR name = 'Saudi Arabia';
UPDATE teams_country SET name = 'Kingdom of Spain' WHERE common_name = 'Spain' OR name = 'Spain';
UPDATE teams_country SET name = 'Kingdom of Sweden' WHERE common_name = 'Sweden' OR name = 'Sweden';
UPDATE teams_country SET name = 'Kingdom of Thailand' WHERE common_name = 'Thailand' OR name = 'Thailand';
UPDATE teams_country SET name = 'Kingdom of the Netherlands' WHERE common_name = 'Netherlands' OR name = 'Netherlands';
UPDATE teams_country SET name = 'Kingdom of Tonga' WHERE common_name = 'Tonga' OR name = 'Tonga';
UPDATE teams_country SET name = 'Kyrgyz Republic' WHERE common_name = 'Kyrgyzstan' OR name = 'Kyrgyzstan';
UPDATE teams_country SET name = 'Lao People''s Democratic Republic' WHERE common_name = 'Laos' OR name = 'Laos';
UPDATE teams_country SET name = 'Lebanese Republic' WHERE common_name = 'Lebanon' OR name = 'Lebanon';
UPDATE teams_country SET name = 'Nation of Brunei, Abode of Peace' WHERE common_name = 'Brunei' OR name = 'Brunei';
UPDATE teams_country SET name = 'Oriental Republic of Uruguay' WHERE common_name = 'Uruguay' OR name = 'Uruguay';
UPDATE teams_country SET name = 'People''s Democratic Republic of Algeria' WHERE common_name = 'Algeria' OR name = 'Algeria';
UPDATE teams_country SET name = 'People''s Republic of Bangladesh' WHERE common_name = 'Bangladesh' OR name = 'Bangladesh';
UPDATE teams_country SET name = 'People''s Republic of China' WHERE common_name = 'China' OR name = 'China';
UPDATE teams_country SET name = 'Plurinational State of Bolivia' WHERE common_name = 'Bolivia' OR name = 'Bolivia';
UPDATE teams_country SET name = 'Portuguese Republic' WHERE common_name = 'Portugal' OR name = 'Portugal';
UPDATE teams_country SET name = 'Principality of Andorra' WHERE common_name = 'Andorra' OR name = 'Andorra';
UPDATE teams_country SET name = 'Principality of Liechtenstein' WHERE common_name = 'Liechtenstein' OR name = 'Liechtenstein';
UPDATE teams_country SET name = 'Principality of Monaco' WHERE common_name = 'Monaco' OR name = 'Monaco';
UPDATE teams_country SET name = 'Republic of Albania' WHERE common_name = 'Albania' OR name = 'Albania';
UPDATE teams_country SET name = 'Republic of Angola' WHERE common_name = 'Angola' OR name = 'Angola';
UPDATE teams_country SET name = 'Republic of Armenia' WHERE common_name = 'Armenia' OR name = 'Armenia';
UPDATE teams_country SET name = 'Republic of Austria' WHERE common_name = 'Austria' OR name = 'Austria';
UPDATE teams_country SET name = 'Republic of Azerbaijan' WHERE common_name = 'Azerbaijan' OR name = 'Azerbaijan';
UPDATE teams_country SET name = 'Republic of Belarus' WHERE common_name = 'Belarus' OR name = 'Belarus';
UPDATE teams_country SET name = 'Republic of Benin' WHERE common_name = 'Benin' OR name = 'Benin';
UPDATE teams_country SET name = 'Republic of Botswana' WHERE common_name = 'Botswana' OR name = 'Botswana';
UPDATE teams_country SET name = 'Republic of Bulgaria' WHERE common_name = 'Bulgaria' OR name = 'Bulgaria';
UPDATE teams_country SET name = 'Republic of Burundi' WHERE common_name = 'Burundi' OR name = 'Burundi';
UPDATE teams_country SET name = 'Republic of Cabo Verde' WHERE common_name = 'Cabo Verde' OR name = 'Cabo Verde';
UPDATE teams_country SET name = 'Republic of Cameroon' WHERE common_name = 'Cameroon' OR name = 'Cameroon';
UPDATE teams_country SET name = 'Republic of Chad' WHERE common_name = 'Chad' OR name = 'Chad';
UPDATE teams_country SET name = 'Republic of Chile' WHERE common_name = 'Chile' OR name = 'Chile';
UPDATE teams_country SET name = 'Republic of Colombia' WHERE common_name = 'Colombia' OR name = 'Colombia';
UPDATE teams_country SET name = 'Republic of Costa Rica' WHERE common_name = 'Costa Rica' OR name = 'Costa Rica';
UPDATE teams_country SET name = 'Republic of Côte d''Ivoire' WHERE common_name = 'Côte d''Ivoire' OR name = 'Côte d''Ivoire';
UPDATE teams_country SET name = 'Republic of Croatia' WHERE common_name = 'Croatia' OR name = 'Croatia';
UPDATE teams_country SET name = 'Republic of Cuba' WHERE common_name = 'Cuba' OR name = 'Cuba';
UPDATE teams_country SET name = 'Republic of Cyprus' WHERE common_name = 'Cyprus' OR name = 'Cyprus';
UPDATE teams_country SET name = 'Republic of Djibouti' WHERE common_name = 'Djibouti' OR name = 'Djibouti';
UPDATE teams_country SET name = 'Republic of Ecuador' WHERE common_name = 'Ecuador' OR name = 'Ecuador';
UPDATE teams_country SET name = 'Republic of El Salvador' WHERE common_name = 'El Salvador' OR name = 'El Salvador';
UPDATE teams_country SET name = 'Republic of Equatorial Guinea' WHERE common_name = 'Equatorial Guinea' OR name = 'Equatorial Guinea';
UPDATE teams_country SET name = 'Republic of Estonia' WHERE common_name = 'Estonia' OR name = 'Estonia';
UPDATE teams_country SET name = 'Republic of Fiji' WHERE common_name = 'Fiji' OR name = 'Fiji';
UPDATE teams_country SET name = 'Republic of Finland' WHERE common_name = 'Finland' OR name = 'Finland';
UPDATE teams_country SET name = 'Republic of Ghana' WHERE common_name = 'Ghana' OR name = 'Ghana';
UPDATE teams_country SET name = 'Republic of Guatemala' WHERE common_name = 'Guatemala' OR name = 'Guatemala';
UPDATE teams_country SET name = 'Republic of Guinea' WHERE common_name = 'Guinea' OR name = 'Guinea';
UPDATE teams_country SET name = 'Republic of Guinea-Bissau' WHERE common_name = 'Guinea-Bissau' OR name = 'Guinea-Bissau';
UPDATE teams_country SET name = 'Republic of Haiti' WHERE common_name = 'Haiti' OR name = 'Haiti';
UPDATE teams_country SET name = 'Republic of Honduras' WHERE common_name = 'Honduras' OR name = 'Honduras';
UPDATE teams_country SET name = 'Republic of India' WHERE common_name = 'India' OR name = 'India';
UPDATE teams_country SET name = 'Republic of Indonesia' WHERE common_name = 'Indonesia' OR name = 'Indonesia';
UPDATE teams_country SET name = 'Republic of Iraq' WHERE common_name = 'Iraq' OR name = 'Iraq';
UPDATE teams_country SET name = 'Republic of Ireland' WHERE common_name = 'Ireland' OR name = 'Ireland';
UPDATE teams_country SET name = 'Republic of Kazakhstan' WHERE common_name = 'Kazakhstan' OR name = 'Kazakhstan';
UPDATE teams_country SET name = 'Republic of Kenya' WHERE common_name = 'Kenya' OR name = 'Kenya';
UPDATE teams_country SET name = 'Republic of Korea' WHERE common_name = 'South Korea' OR name = 'South Korea';
UPDATE teams_country SET name = 'Republic of Latvia' WHERE common_name = 'Latvia' OR name = 'Latvia';
UPDATE teams_country SET name = 'Republic of Liberia' WHERE common_name = 'Liberia' OR name = 'Liberia';
UPDATE teams_country SET name = 'Republic of Lithuania' WHERE common_name = 'Lithuania' OR name = 'Lithuania';
UPDATE teams_country SET name = 'Republic of Madagascar' WHERE common_name = 'Madagascar' OR name = 'Madagascar';
UPDATE teams_country SET name = 'Republic of Malawi' WHERE common_name = 'Malawi' OR name = 'Malawi';
UPDATE teams_country SET name = 'Republic of Mali' WHERE common_name = 'Mali' OR name = 'Mali';
UPDATE teams_country SET name = 'Republic of Malta' WHERE common_name = 'Malta' OR name = 'Malta';
UPDATE teams_country SET name = 'Republic of Mauritius' WHERE common_name = 'Mauritius' OR name = 'Mauritius';
UPDATE teams_country SET name = 'Republic of Moldova' WHERE common_name = 'Moldova' OR name = 'Moldova';
UPDATE teams_country SET name = 'Republic of Mozambique' WHERE common_name = 'Mozambique' OR name = 'Mozambique';
UPDATE teams_country SET name = 'Republic of Namibia' WHERE common_name = 'Namibia' OR name = 'Namibia';
UPDATE teams_country SET name = 'Republic of Nauru' WHERE common_name = 'Nauru' OR name = 'Nauru';
UPDATE teams_country SET name = 'Republic of Nicaragua' WHERE common_name = 'Nicaragua' OR name = 'Nicaragua';
UPDATE teams_country SET name = 'Republic of Niger' WHERE common_name = 'Niger' OR name = 'Niger';
UPDATE teams_country SET name = 'Republic of North Macedonia' WHERE common_name = 'North Macedonia' OR name = 'North Macedonia';
UPDATE teams_country SET name = 'Republic of Palau' WHERE common_name = 'Palau' OR name = 'Palau';
UPDATE teams_country SET name = 'Republic of Panama' WHERE common_name = 'Panama' OR name = 'Panama';
UPDATE teams_country SET name = 'Republic of Paraguay' WHERE common_name = 'Paraguay' OR name = 'Paraguay';
UPDATE teams_country SET name = 'Republic of Peru' WHERE common_name = 'Peru' OR name = 'Peru';
UPDATE teams_country SET name = 'Republic of Poland' WHERE common_name = 'Poland' OR name = 'Poland';
UPDATE teams_country SET name = 'Republic of Rwanda' WHERE common_name = 'Rwanda' OR name = 'Rwanda';
UPDATE teams_country SET name = 'Republic of San Marino' WHERE common_name = 'San Marino' OR name = 'San Marino';
UPDATE teams_country SET name = 'Republic of Senegal' WHERE common_name = 'Senegal' OR name = 'Senegal';
UPDATE teams_country SET name = 'Republic of Serbia' WHERE common_name = 'Serbia' OR name = 'Serbia';
UPDATE teams_country SET name = 'Republic of Seychelles' WHERE common_name = 'Seychelles' OR name = 'Seychelles';
UPDATE teams_country SET name = 'Republic of Sierra Leone' WHERE common_name = 'Sierra Leone' OR name = 'Sierra Leone';
UPDATE teams_country SET name = 'Republic of Singapore' WHERE common_name = 'Singapore' OR name = 'Singapore';
UPDATE teams_country SET name = 'Republic of Slovenia' WHERE common_name = 'Slovenia' OR name = 'Slovenia';
UPDATE teams_country SET name = 'Republic of South Africa' WHERE common_name = 'South Africa' OR name = 'South Africa';
UPDATE teams_country SET name = 'Republic of South Sudan' WHERE common_name = 'South Sudan' OR name = 'South Sudan';
UPDATE teams_country SET name = 'Republic of Suriname' WHERE common_name = 'Suriname' OR name = 'Suriname';
UPDATE teams_country SET name = 'Republic of Tajikistan' WHERE common_name = 'Tajikistan' OR name = 'Tajikistan';
UPDATE teams_country SET name = 'Republic of the Congo' WHERE common_name = 'Congo' OR name = 'Congo';
UPDATE teams_country SET name = 'Republic of the Gambia' WHERE common_name = 'Gambia' OR name = 'Gambia';
UPDATE teams_country SET name = 'Republic of the Maldives' WHERE common_name = 'Maldives' OR name = 'Maldives';
UPDATE teams_country SET name = 'Republic of the Marshall Islands' WHERE common_name = 'Marshall Islands' OR name = 'Marshall Islands';
UPDATE teams_country SET name = 'Republic of the Philippines' WHERE common_name = 'Philippines' OR name = 'Philippines';
UPDATE teams_country SET name = 'Republic of the Sudan' WHERE common_name = 'Sudan' OR name = 'Sudan';
UPDATE teams_country SET name = 'Republic of the Union of Myanmar' WHERE common_name = 'Myanmar' OR name = 'Myanmar';
UPDATE teams_country SET name = 'Republic of Trinidad and Tobago' WHERE common_name = 'Trinidad and Tobago' OR name = 'Trinidad and Tobago';
UPDATE teams_country SET name = 'Republic of Turkey' WHERE common_name = 'Turkey' OR name = 'Turkey';
UPDATE teams_country SET name = 'Republic of Uganda' WHERE common_name = 'Uganda' OR name = 'Uganda';
UPDATE teams_country SET name = 'Republic of Uzbekistan' WHERE common_name = 'Uzbekistan' OR name = 'Uzbekistan';
UPDATE teams_country SET name = 'Republic of Vanuatu' WHERE common_name = 'Vanuatu' OR name = 'Vanuatu';
UPDATE teams_country SET name = 'Republic of Yemen' WHERE common_name = 'Yemen' OR name = 'Yemen';
UPDATE teams_country SET name = 'Republic of Zambia' WHERE common_name = 'Zambia' OR name = 'Zambia';
UPDATE teams_country SET name = 'Republic of Zimbabwe' WHERE common_name = 'Zimbabwe' OR name = 'Zimbabwe';
UPDATE teams_country SET name = 'Russian Federation' WHERE common_name = 'Russia' OR name = 'Russia';
UPDATE teams_country SET name = 'Slovak Republic' WHERE common_name = 'Slovakia' OR name = 'Slovakia';
UPDATE teams_country SET name = 'Socialist Republic of Vietnam' WHERE common_name = 'Vietnam' OR name = 'Vietnam';
UPDATE teams_country SET name = 'State of Eritrea' WHERE common_name = 'Eritrea' OR name = 'Eritrea';
UPDATE teams_country SET name = 'State of Israel' WHERE common_name = 'Israel' OR name = 'Israel';
UPDATE teams_country SET name = 'State of Kuwait' WHERE common_name = 'Kuwait' OR name = 'Kuwait';
UPDATE teams_country SET name = 'State of Libya' WHERE common_name = 'Libya' OR name = 'Libya';
UPDATE teams_country SET name = 'State of Qatar' WHERE common_name = 'Qatar' OR name = 'Qatar';
UPDATE teams_country SET name = 'Sultanate of Oman' WHERE common_name = 'Oman' OR name = 'Oman';
UPDATE teams_country SET name = 'Swiss Confederation' WHERE common_name = 'Switzerland' OR name = 'Switzerland';
UPDATE teams_country SET name = 'Syrian Arab Republic' WHERE common_name = 'Syria' OR name = 'Syria';
UPDATE teams_country SET name = 'Togolese Republic' WHERE common_name = 'Togo' OR name = 'Togo';
UPDATE teams_country SET name = 'Tunisian Republic' WHERE common_name = 'Tunisia' OR name = 'Tunisia';
UPDATE teams_country SET name = 'Union of the Comoros' WHERE common_name = 'Comoros' OR name = 'Comoros';
UPDATE teams_country SET name = 'United Kingdom of Great Britain and Northern Ireland' WHERE common_name = 'United Kingdom' OR name = 'United Kingdom';
UPDATE teams_country SET name = 'United Mexican States' WHERE common_name = 'Mexico' OR name = 'Mexico';
UPDATE teams_country SET name = 'United Republic of Tanzania' WHERE common_name = 'Tanzania' OR name = 'Tanzania';
UPDATE teams_country SET name = 'United States of America' WHERE common_name = 'United States' OR name = 'United States';

-- For rows that were already common-named and unchanged (Canada, Japan, etc.),
-- ensure common_name is filled.
UPDATE teams_country
SET common_name = name
WHERE common_name IS NULL OR TRIM(common_name) = '';

