/**
 * Generate sql/add_teams_country_common_name.sql
 * Run: node sql/generate_common_name_sql.js
 */
const fs = require('fs');
const path = require('path');

const COMMON_NAMES = {
  'Antigua and Barbuda': 'Antigua and Barbuda',
  'Arab Republic of Egypt': 'Egypt',
  'Argentine Republic': 'Argentina',
  Barbados: 'Barbados',
  Belize: 'Belize',
  'Bolivarian Republic of Venezuela': 'Venezuela',
  'Bosnia and Herzegovina': 'Bosnia and Herzegovina',
  'Burkina Faso': 'Burkina Faso',
  Canada: 'Canada',
  'Central African Republic': 'Central African Republic',
  'Co-operative Republic of Guyana': 'Guyana',
  'Commonwealth of Australia': 'Australia',
  'Commonwealth of Dominica': 'Dominica',
  'Commonwealth of the Bahamas': 'Bahamas',
  'Czech Republic': 'Czechia',
  "Democratic People's Republic of Korea": 'North Korea',
  'Democratic Republic of São Tomé and Príncipe': 'São Tomé and Príncipe',
  'Democratic Republic of the Congo': 'DR Congo',
  'Democratic Republic of Timor-Leste': 'Timor-Leste',
  'Democratic Socialist Republic of Sri Lanka': 'Sri Lanka',
  'Dominican Republic': 'Dominican Republic',
  'Federal Democratic Republic of Ethiopia': 'Ethiopia',
  'Federal Democratic Republic of Nepal': 'Nepal',
  'Federal Republic of Germany': 'Germany',
  'Federal Republic of Nigeria': 'Nigeria',
  'Federal Republic of Somalia': 'Somalia',
  'Federated States of Micronesia': 'Micronesia',
  'Federation of Saint Christopher and Nevis': 'Saint Kitts and Nevis',
  'Federative Republic of Brazil': 'Brazil',
  'French Republic': 'France',
  'Gabonese Republic': 'Gabon',
  Georgia: 'Georgia',
  'Grand Duchy of Luxembourg': 'Luxembourg',
  Grenada: 'Grenada',
  'Hashemite Kingdom of Jordan': 'Jordan',
  'Hellenic Republic': 'Greece',
  Hungary: 'Hungary',
  Iceland: 'Iceland',
  'Independent and Sovereign Republic of Kiribati': 'Kiribati',
  'Independent State of Papua New Guinea': 'Papua New Guinea',
  'Independent State of Samoa': 'Samoa',
  'Islamic Republic of Afghanistan': 'Afghanistan',
  'Islamic Republic of Iran': 'Iran',
  'Islamic Republic of Mauritania': 'Mauritania',
  'Islamic Republic of Pakistan': 'Pakistan',
  'Italian Republic': 'Italy',
  Jamaica: 'Jamaica',
  Japan: 'Japan',
  'Kingdom of Bahrain': 'Bahrain',
  'Kingdom of Belgium': 'Belgium',
  'Kingdom of Bhutan': 'Bhutan',
  'Kingdom of Cambodia': 'Cambodia',
  'Kingdom of Denmark': 'Denmark',
  'Kingdom of Eswatini': 'Eswatini',
  'Kingdom of Lesotho': 'Lesotho',
  'Kingdom of Morocco': 'Morocco',
  'Kingdom of Norway': 'Norway',
  'Kingdom of Saudi Arabia': 'Saudi Arabia',
  'Kingdom of Spain': 'Spain',
  'Kingdom of Sweden': 'Sweden',
  'Kingdom of Thailand': 'Thailand',
  'Kingdom of the Netherlands': 'Netherlands',
  'Kingdom of Tonga': 'Tonga',
  'Kyrgyz Republic': 'Kyrgyzstan',
  "Lao People's Democratic Republic": 'Laos',
  'Lebanese Republic': 'Lebanon',
  Malaysia: 'Malaysia',
  Mongolia: 'Mongolia',
  Montenegro: 'Montenegro',
  'Nation of Brunei, Abode of Peace': 'Brunei',
  'New Zealand': 'New Zealand',
  'Oriental Republic of Uruguay': 'Uruguay',
  "People's Democratic Republic of Algeria": 'Algeria',
  "People's Republic of Bangladesh": 'Bangladesh',
  "People's Republic of China": 'China',
  'Plurinational State of Bolivia': 'Bolivia',
  'Portuguese Republic': 'Portugal',
  'Principality of Andorra': 'Andorra',
  'Principality of Liechtenstein': 'Liechtenstein',
  'Principality of Monaco': 'Monaco',
  'Republic of Albania': 'Albania',
  'Republic of Angola': 'Angola',
  'Republic of Armenia': 'Armenia',
  'Republic of Austria': 'Austria',
  'Republic of Azerbaijan': 'Azerbaijan',
  'Republic of Belarus': 'Belarus',
  'Republic of Benin': 'Benin',
  'Republic of Botswana': 'Botswana',
  'Republic of Bulgaria': 'Bulgaria',
  'Republic of Burundi': 'Burundi',
  'Republic of Cabo Verde': 'Cabo Verde',
  'Republic of Cameroon': 'Cameroon',
  'Republic of Chad': 'Chad',
  'Republic of Chile': 'Chile',
  'Republic of Colombia': 'Colombia',
  'Republic of Costa Rica': 'Costa Rica',
  "Republic of Côte d'Ivoire": "Côte d'Ivoire",
  'Republic of Croatia': 'Croatia',
  'Republic of Cuba': 'Cuba',
  'Republic of Cyprus': 'Cyprus',
  'Republic of Djibouti': 'Djibouti',
  'Republic of Ecuador': 'Ecuador',
  'Republic of El Salvador': 'El Salvador',
  'Republic of Equatorial Guinea': 'Equatorial Guinea',
  'Republic of Estonia': 'Estonia',
  'Republic of Fiji': 'Fiji',
  'Republic of Finland': 'Finland',
  'Republic of Ghana': 'Ghana',
  'Republic of Guatemala': 'Guatemala',
  'Republic of Guinea': 'Guinea',
  'Republic of Guinea-Bissau': 'Guinea-Bissau',
  'Republic of Haiti': 'Haiti',
  'Republic of Honduras': 'Honduras',
  'Republic of India': 'India',
  'Republic of Indonesia': 'Indonesia',
  'Republic of Iraq': 'Iraq',
  'Republic of Ireland': 'Ireland',
  'Republic of Kazakhstan': 'Kazakhstan',
  'Republic of Kenya': 'Kenya',
  'Republic of Korea': 'South Korea',
  'Republic of Latvia': 'Latvia',
  'Republic of Liberia': 'Liberia',
  'Republic of Lithuania': 'Lithuania',
  'Republic of Madagascar': 'Madagascar',
  'Republic of Malawi': 'Malawi',
  'Republic of Mali': 'Mali',
  'Republic of Malta': 'Malta',
  'Republic of Mauritius': 'Mauritius',
  'Republic of Moldova': 'Moldova',
  'Republic of Mozambique': 'Mozambique',
  'Republic of Namibia': 'Namibia',
  'Republic of Nauru': 'Nauru',
  'Republic of Nicaragua': 'Nicaragua',
  'Republic of Niger': 'Niger',
  'Republic of North Macedonia': 'North Macedonia',
  'Republic of Palau': 'Palau',
  'Republic of Panama': 'Panama',
  'Republic of Paraguay': 'Paraguay',
  'Republic of Peru': 'Peru',
  'Republic of Poland': 'Poland',
  'Republic of Rwanda': 'Rwanda',
  'Republic of San Marino': 'San Marino',
  'Republic of Senegal': 'Senegal',
  'Republic of Serbia': 'Serbia',
  'Republic of Seychelles': 'Seychelles',
  'Republic of Sierra Leone': 'Sierra Leone',
  'Republic of Singapore': 'Singapore',
  'Republic of Slovenia': 'Slovenia',
  'Republic of South Africa': 'South Africa',
  'Republic of South Sudan': 'South Sudan',
  'Republic of Suriname': 'Suriname',
  'Republic of Tajikistan': 'Tajikistan',
  'Republic of the Congo': 'Congo',
  'Republic of the Gambia': 'Gambia',
  'Republic of the Maldives': 'Maldives',
  'Republic of the Marshall Islands': 'Marshall Islands',
  'Republic of the Philippines': 'Philippines',
  'Republic of the Sudan': 'Sudan',
  'Republic of the Union of Myanmar': 'Myanmar',
  'Republic of Trinidad and Tobago': 'Trinidad and Tobago',
  'Republic of Turkey': 'Turkey',
  'Republic of Uganda': 'Uganda',
  'Republic of Uzbekistan': 'Uzbekistan',
  'Republic of Vanuatu': 'Vanuatu',
  'Republic of Yemen': 'Yemen',
  'Republic of Zambia': 'Zambia',
  'Republic of Zimbabwe': 'Zimbabwe',
  Romania: 'Romania',
  'Russian Federation': 'Russia',
  'Saint Lucia': 'Saint Lucia',
  'Saint Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
  'Slovak Republic': 'Slovakia',
  'Socialist Republic of Vietnam': 'Vietnam',
  'Solomon Islands': 'Solomon Islands',
  'State of Eritrea': 'Eritrea',
  'State of Israel': 'Israel',
  'State of Kuwait': 'Kuwait',
  'State of Libya': 'Libya',
  'State of Qatar': 'Qatar',
  'Sultanate of Oman': 'Oman',
  'Swiss Confederation': 'Switzerland',
  'Syrian Arab Republic': 'Syria',
  'Togolese Republic': 'Togo',
  'Tunisian Republic': 'Tunisia',
  Turkmenistan: 'Turkmenistan',
  Tuvalu: 'Tuvalu',
  Ukraine: 'Ukraine',
  'Union of the Comoros': 'Comoros',
  'United Arab Emirates': 'United Arab Emirates',
  'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom',
  'United Mexican States': 'Mexico',
  'United Republic of Tanzania': 'Tanzania',
  'United States of America': 'United States'
};

function sqlStr(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

const lines = [];
lines.push('-- teams_country: add common_name and populate it');
lines.push('-- Safe to run once. If the column already exists, skip the ALTER.');
lines.push('');
lines.push('ALTER TABLE teams_country');
lines.push('  ADD COLUMN common_name VARCHAR(255) NULL AFTER name;');
lines.push('');
lines.push('-- Because name was previously overwritten with common names, copy name -> common_name first.');
lines.push('UPDATE teams_country');
lines.push('SET common_name = name');
lines.push('WHERE common_name IS NULL OR TRIM(common_name) = \'\';');
lines.push('');
lines.push('-- Restore official formal names into name where we know the mapping.');
Object.entries(COMMON_NAMES).forEach(([formal, common]) => {
  if (formal === common) return;
  lines.push(
    `UPDATE teams_country SET name = ${sqlStr(formal)} WHERE common_name = ${sqlStr(common)} OR name = ${sqlStr(common)};`
  );
});
lines.push('');
lines.push('-- For rows that were already common-named and unchanged (Canada, Japan, etc.),');
lines.push('-- ensure common_name is filled.');
lines.push('UPDATE teams_country');
lines.push('SET common_name = name');
lines.push('WHERE common_name IS NULL OR TRIM(common_name) = \'\';');
lines.push('');

const out = path.join(__dirname, 'add_teams_country_common_name.sql');
fs.writeFileSync(out, `${lines.join('\n')}\n`, 'utf8');
console.log(`Wrote ${out}`);
